config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :ingredients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
    has_many :dishes_ingredients
    has_many :ingredients, through: :dishes_ingredients
    accepts_nested_attributes_for :ingredients, allow_destroy: true
  end
  

app/models/dishes_ingredient.rb
class DishesIngredient < ApplicationRecord
  belongs_to :dish
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :dishes_ingredients
    has_many :dishes, through: :dishes_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
# PATH:  app\controllers\dishes_controller.rb

class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully created." }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Dish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

    #|--------------------------------------------
    #| Modified the code to cater for the nested form
    #|
    def dish_params
      params.require(:dish).permit(:name, ingredients_attributes: [:id, :ingredient_name, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
        # Any logic needed for your homepage
    end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.find_or_initialize_by(name: ingredient_params[:name])
    if @ingredient.new_record?
      @ingredient.quantity = ingredient_params[:quantity]
    else
      @ingredient.quantity += ingredient_params[:quantity].to_i
    end

    if @ingredient.save
      redirect_to ingredients_path, notice: 'Ingredient saved successfully'
    else
      render :new
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    #|----------------------------------------------------
    #|  This helper method is used for dynamically adding nested
    #|  form fields without reloading the page. 
    #|  
    #|  Reference of the Guide
    #|      ^ https://dev.to/ndrean/dynamic-nested-form-in-rails-4k9p
    #|
    def link_to_add_fields(name, f, association)

        # --> Creates a new instance of the associated object
        new_object = f.object.send(association).klass.new

        # -->  Generates a unique ID for the new object
        id = new_object.object_id

        # -->  Generates form fields for the new object and then renders a partial for the fields, using the form builder
        fields = f.fields_for(association, new_object, child_index: id) do |builder|
          render(association.to_s.singularize + "_fields", f: builder)
        end

        # --> Returns a link that, when clicked, will add the new fields to the form
        link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
      end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
  <p>
    <strong>Name:</strong>
    <%= dish.name %>
  </p>

  <p>
    <strong>Ingredient:</strong>
    <%= dish.ingredient_id %>
  </p>

</div>

app/views/dishes/_form.html.erb
<%= form_with(model: @dish, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <h3>Ingredients:</h3>
  <div id="ingredients">
    <%= form.fields_for :ingredients do |ingredient_form| %>
      <%= render 'ingredient_fields', f: ingredient_form %>
    <% end %>
  </div>
  <div class="actions">
    <%= link_to_add_fields "Add Ingredient", form, :ingredients %>
  </div>

  <%= form.submit %>
<% end %>

app/views/dishes/_ingredient_fields.html.erb
<!-- _ingredient_fields.html.erb -->
<div class="nested-fields">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.hidden_field :_destroy %>
    <%= link_to 'Remove', '#', class: 'remove-ingredient' %>
</div>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= form_with(model: @dish, local: true) do |form| %>
  
  <!-- Fields for Dish -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <!-- Nested Fields for Ingredients -->
  <h3>Ingredients:</h3>
  <div id="ingredients">
    <%= form.fields_for :ingredients do |ingredient_form| %>
      <!-- Render a partial for ingredient fields -->
      <%= render 'ingredient_fields', f: ingredient_form %>
    <% end %>
  </div>

  <!-- Link to add more ingredient fields (handled by JavaScript) -->
  <%= link_to 'Add Ingredient', '#', id: 'add-ingredient' %>

  <!-- Submit Button -->
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/dishes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dishes</h1>

<div id="dishes">
  <% @dishes.each do |dish| %>
    <%= render dish %>
    <p>
      <%= link_to "Show this dish", dish %>
    </p>
  <% end %>
</div>

<%= link_to "New dish", new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= form_with(model: @dish, local: true) do |form| %>
  
  <!-- Fields for Dish -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <!-- Nested Fields for Ingredients -->
  <h3>Ingredients:</h3>
  <div id="ingredients">
    <%= form.fields_for :ingredients do |ingredient_form| %>
      <!-- Render a partial for ingredient fields -->
      <%= render 'ingredient_fields', f: ingredient_form %>
    <% end %>
  </div>

  <!-- Link to add more ingredient fields (handled by JavaScript) -->
  <%= link_to 'Add Ingredient', '#', id: 'add-ingredient' %>

  <!-- Submit Button -->
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/dishes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dish %>

<div>
  <%= link_to "Edit this dish", edit_dish_path(@dish) %> |
  <%= link_to "Back to dishes", dishes_path %>

  <%= button_to "Destroy this dish", @dish, method: :delete %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="app/assets/stylesheets/home.css" rel="stylesheet">
    
    <title> Recipe Planner</title>
    
</head>
<body>

    <h1 class="text-center bg-success bg-gradient h1-custom">
        Recipe Planner
    </h1>
  

    <!-- Bootstrap Bundle with Popper (includes Popper for dropdowns, tooltips, and popovers) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

    
    <div class="container">
       <div class="row">
            <div class="col-md-6 background-with-mask col-min-height-set col-max-height-set background-column-1 ">
                <a href="/dishes" class="overlay-text-link">
                    <div class="overlay-text">
                        <span class="text-background">
                            View Dishes
                        </span>
                    </div>
                </a>
                
            </div>

            <div class="col-md-6 background-with-mask col-min-height-set col-max-height-set background-column-2">
                <a href="/ingredients" class="overlay-text-link">
                    <div class="overlay-text">
                        <span class="text-background">
                            View Stock Ingredients
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>


</body>

</html>

app/views/ingredients/_form.html.erb
<!-- PATH: app\views\ingredients\_form.html.erb -->

<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<!-- PATH:  app\views\ingredients\_ingredient.html.erb-->

<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= ingredient.quantity %>
  </p>

</div>

<%= link_to 'Back to Ingredients List', ingredients_path %>

app/views/ingredients/edit.html.erb
<!-- PATH: app\views\ingredients\edit.html.erb -->

<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<!-- PATH: app\views\ingredients\index.html.erb -->

<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

app/views/ingredients/new.html.erb
<!-- PATH: app\views\ingredients\new.html.erb -->

<h1>New ingredient</h1>

<%= form_with(model: @ingredient, url: ingredients_path) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>
  <%= form.submit "Save" %>
<% end %>

app/views/ingredients/show.html.erb
<!-- PATH: app\views\ingredients\show.html.erb -->

<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DishRecipePlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>